function result=run_tests_by_factory(className, varargin)

    if (strcmp(className, 'GenEllipsoid')) || (strcmp(className, 'ellipsoid'))
        import elltool.core.test.EllFactory;
        %It seems to be very good, but it does not work :((
        %         runner = mlunitext.text_test_runner(1, 1);
        %         testCaseList = {'EllipsoidIntUnionTC',...
        %             'EllipsoidTestCase',...
        %             'EllipsoidSecTestCase',...
        %             'EllipsoidSecTestCase',...
        %             'HyperplaneTestCase',...
        %             'ElliIntUnionTCMultiDim',...
        %             'EllTCMultiDim',...
        %             'EllSecTCMultiDim',...
        %             'MPTIntegrationTestCase',...
        %             'EllipsoidPlotTestCase',...
        %             'EllAuxTestCase',...
        %             'HyperplanePlotTestCase',...
        %             'EllipsoidMinkPlotTestCase',...
        %             'EllipsoidBasicSecondTC',...
        %             'EllipsoidDispStructTC',...
        %             'HyperplaneDispStructTC'
        %             };
        %
        %         testCaseList = strcat('elltool.core.test.mlunit.',testCaseList);
        %         suite = mlunitext.test_suite.fromTestCaseNameList(testCaseList,{EllFactory(className)});
        %         result = runner.run(suite);
        runner = mlunitext.text_test_runner(1, 1);
        loader = mlunitext.test_loader;
        suiteList = {};
        %Tests for ellipsoid class;
        %1
        suiteList{end + 1} = loader.load_tests_from_test_case(...
            'elltool.core.test.mlunit.EllipsoidIntUnionTC', ...
            EllFactory(className));
%         %2
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.EllipsoidTestCase', ...
%             EllFactory(className));
%         %3
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.EllipsoidSecTestCase', ...
%             EllFactory(className));
%         %4
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.HyperplaneTestCase', ...
%             EllFactory(className));
%         %5
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.ElliIntUnionTCMultiDim', ...
%             EllFactory(className));
%         % %6
%         % suiteList{end + 1} = loader.load_tests_from_test_case(...
%         %     'elltool.core.test.mlunit.EllTCMultiDim', ...
%         %     EllFactory(className));
%         % %7
%         % suiteList{end + 1} = loader.load_tests_from_test_case(...
%         %     'elltool.core.test.mlunit.EllSecTCMultiDim', ...
%         %     EllFactory(className));
%         %8
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.MPTIntegrationTestCase', ...
%             EllFactory(className));
%         %9
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.EllipsoidPlotTestCase', ...
%             EllFactory(className));
%         %10
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.EllAuxTestCase', ...
%             EllFactory(className));
%         %11
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.HyperplanePlotTestCase', ...
%             EllFactory(className));
%         %12
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.EllipsoidMinkPlotTestCase', ...
%             EllFactory(className));
%         %13
%         suiteList{end + 1} = loader.load_tests_from_test_case(...
%             'elltool.core.test.mlunit.EllipsoidBasicSecondTC', ...
%             EllFactory(className));
%         % %14
%         % suiteList{end + 1} = loader.load_tests_from_test_case(...
%         %     'elltool.core.test.mlunit.EllipsoidDispStructTC', ...
%         %     EllFactory(className));
%         % %15
%         % suiteList{end + 1} = loader.load_tests_from_test_case(...
%         %     'elltool.core.test.mlunit.HyperplaneDispStructTC', ...
%         %     EllFactory(className));
%         if (strcmp(className, 'GenEllipsoid'))
%             %16
%             suiteList{end + 1} = loader.load_tests_from_test_case(...
%                 'elltool.core.test.mlunit.GenEllipsoidPlotTestCase', ...
%                 EllFactory(className));
%             %17
%             suiteList{end + 1} = loader.load_tests_from_test_case(...
%                 'elltool.core.test.mlunit.GenEllipsoidTestCase', ...
%                 EllFactory(className));
%        end

        testLists = cellfun(@(x)x.tests,suiteList,'UniformOutput',false);
        testList=horzcat(testLists{:});
        suite = mlunitext.test_suite(testList);
        suite=suite.getCopyFiltered(varargin{:});
        result=runner.run(suite);
    else
        'Wrong name of class for EllFactory';
    end
